server:
  port: 9090

spring:
  # 数据库配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/takeout?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root

  servlet:
    multipart:
      # 上传文件大小限制
      max-file-size: 10MB

# mybatis-plus相关配置
mybatis-plus:
  # 配置xml文件所在位置
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  configuration:
    # 控制台打印SQL语句，建议开发模式开启
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    # 关闭自带的banner
    banner: false
    db-config:
      id-type: assign_id
